bio.tools live deploy
BioSchemas/bioschemas.github.io pull request #349
Opened 2020-12-14 11:33 UTC by albangaignard

Update of the web site for Bio.Tools live deploy

2020-12-14 12:01 UTC, matuskalas commented
Nice @albangaignard ! 🥇 

Aren't you using **0.4-DRAFT** version of the profile?

2020-12-14 13:07 UTC, albangaignard commented
Thanks @matuskalas , indeed, it was 0.4 (in 0.5 outputData has been changed to serviceOutput).

2020-12-15 16:25 UTC, AlasdairGray requested changes
Resource url should be `https://bio.tools`

Other than that it looks good

2020-12-15 16:27 UTC, AlasdairGray approved these changes

2020-12-15 16:27 UTC, merged