Study 0.2 draft
BioSchemas/bioschemas.github.io pull request #350
Opened 2020-12-16 16:43 UTC by AlasdairGray

Updating study profile based on discussions with plant community, and doing various bits of housekeeping.

Profile is consistent with schema v11.01 and Study v0.3-DRAFT.

0.3 version of the profile will need to incorporate the changes that result from [issue 472](https://github.com/BioSchemas/specifications/issues/472)

2020-12-16 20:07 UTC, ljgarcia requested changes
In addition to inline comments:
* Type contributors appears empty
* Group has no leaders nor objectives
* Link to examples does not work
* Tasks and issues is the same for the type and the profile
* There are no use cases

2020-12-16 20:07 UTC, ljgarcia commented on _types/Study/0.3-DRAFT.html
> +description: "Study"
Could this description be improved?

2020-12-16 20:07 UTC, ljgarcia commented on _profiles/Study/0.2-DRAFT.html
> +- CreativeWork
Being this the Study type profile, should not the hierarchy be Thing-CreativeWork-Study?

2020-12-17 09:08 UTC, AlasdairGray commented
> * Group has no leaders nor objectives

Covered in [issue 258](https://github.com/BioSchemas/specifications/issues/258), while not ideal we should still let the work proceed.

2020-12-17 09:08 UTC, AlasdairGray commented
> * Tasks and issues is the same for the type and the profile

This is the same for all specifications.

2020-12-17 09:13 UTC, AlasdairGray commented
> * Type contributors appears empty

Contributors for types is auto populated from the group membership, so again should not prevent us from publishing this for now.

2020-12-17 09:17 UTC, AlasdairGray commented
> * Link to examples does not work

Link now fixed, and enabled live deploy link (bb49eb13dcd19c07e86973f8c56d35ccbde44503)

2020-12-17 09:18 UTC, AlasdairGray commented on _types/Study/0.3-DRAFT.html
> +description: "Study"
Already raised in issue 286

2020-12-17 09:20 UTC, AlasdairGray commented on _types/Study/0.3-DRAFT.html
> +---
Not for me, maybe you have visited one but not the other

2020-12-17 09:21 UTC, AlasdairGray commented on _data/type_versions.yaml
> +    latest_publication: "0.3-DRAFT"
No, dates were only put in when version numbers were not unique. It is a lot easier if our version numbers do not have dates.

2020-12-17 09:21 UTC, AlasdairGray commented on _data/profile_versions.yaml
> +    latest_publication: "0.2-DRAFT"
No, dates were only added when the version numbers were not unique.

2020-12-17 09:22 UTC, AlasdairGray commented
@ljgarcia that's all your issues either resolved or tracked as issues for a future draft revision

2020-12-18 16:56 UTC, ljgarcia commented
All issues addressed, thanks.

2020-12-18 16:56 UTC, ljgarcia approved these changes

2021-01-06 10:42 UTC, merged