First try in making a table of contents
BioSchemas/bioschemas.github.io pull request #411
Opened 2021-05-26 12:39 UTC by bedroesb

This PR will bring a TOC to the tutorials that indexes H2 and H3 headings (can be changed):

![Screenshot from 2021-05-26 14-36-28](https://user-images.githubusercontent.com/44875756/119660695-d28b0a80-be2f-11eb-983a-9381fc96dd43.png)

- makes use of [jekyll-table-of-contents](https://github.com/ghiculescu/jekyll-table-of-contents)
- deleted some unused dependencies
- got rid of a java script error by loading the jquery in the head of the website
- used some simple css for now, can be changed

2021-05-26 12:40 UTC, bedroesb commented on _includes/head.html
> +  <script src="{{ 'js/toc.js' | relative_url }}"></script>
to do: only there when layout == tutorial

2021-06-02 08:14 UTC, AlasdairGray commented
@bedroesb when I click on a link in the ToC it jumps down but the heading is hidden below the navigation bar. Is there any way of ensuring that the heading stays on the screen?

2021-06-02 08:15 UTC, AlasdairGray requested changes
Looks nice. Can we add 'Table of Contents' as bold text at the top of the box?

2021-06-02 10:09 UTC, bedroesb commented
@AlasdairGray I did a fix following this [tutorial](https://css-tricks.com/hash-tag-links-padding/) but it still feels a bit hacky, but it works though. I also took the freedom to change all the shadows to the same type used in the frontpage for consistency. I noticed that in mobile mode many things change including the fact that the title disappears and the navigation titles change.  For me it is confusing that in the normal website you don't have the word `tutorial` in the navigation, but you do have it in mobile mode. I could also not follow well the separation between the stylesheet.css and the other scss files. I think if you move everything over to the scss and make more use of the bootstrap classes, the code could be a lot simplified :) Just some thoughts! Sorry if I am commenting things that are already discussed in the past!

2021-06-02 12:12 UTC, AlasdairGray commented
Thanks for the tweaks @bedroesb. Works well for `<h2>`, still not working well for `<h3>`, not sure why that should be the case since the changes you've made look like they should work.

@ljgarcia I've added a 'Table of Contents' title. Hopefully you approve of that.
![Screen Shot 2021-06-02 at 13 11 12](https://user-images.githubusercontent.com/1141265/120477788-1340d180-c3a4-11eb-8fbc-cf417e4161f3.png)

2021-06-02 14:52 UTC, ljgarcia commented
@AlasdairGray looks good. If all the changes you requested have been addressed (I did not check that in detail), please go ahead and merge this PR. Thanks

2021-06-02 14:53 UTC, AlasdairGray approved these changes

2021-06-02 14:53 UTC, merged