Unify redirections
BioSchemas/bioschemas.github.io pull request #491
Opened 2021-11-19 13:29 UTC by ljgarcia

Profile redirections were not always the same, this is an attempt to unify them

2021-11-19 13:29 UTC, ljgarcia commented
@bedroesb if you come up with an idea on how to add this to a template or so, it would be great!

2021-11-19 13:36 UTC, bedroesb commented
@ljgarcia haha I was looking into it on how to specify the redirect_from on a global level, but I did not find a solution. 

at this moment pages have the permalink without the backslash, an I tried to redirect from links with a backslash, but it appears that this redirect is not working on collection level, and can probably be taken out.

```yml
collections_dir: pages
collections:
  types:
    output: true
    permalink: /:collection/:path
    redirect_from:
      - "/:collection/:path/"
  meetings:
    output: true
    permalink: /:collection/:path
    redirect_from:
      - "/:collection/:path/"
  tutorials:
    output: true
    permalink: /:collection/:path
    redirect_from:
      - "/:collection/:path/"
```

I hope you scripted the redirects because this seemed like a lot of work :D

2021-11-19 13:43 UTC, ljgarcia commented
It was a lot of copy&paste.
Those profiles that have a draft after a release are slightly different from the others that only have drafts or have a release as latest option

2021-11-19 13:54 UTC, bedroesb commented
good job nevertheless!

2021-11-22 09:47 UTC, AlasdairGray requested changes
I think there are few copy/paste errors

Really good job in making these consistent. I'd been slowly doing this as we had revisions of profiles.

2021-11-22 09:47 UTC, AlasdairGray commented on pages/_profiles/Event/0.2-DRAFT-2019_06_14.html
> +- "/devSpecs/Beacon/specification/"
Should these be Event?

2021-11-22 09:47 UTC, AlasdairGray commented on pages/_profiles/Person/0.2-DRAFT-2019_07_19.html
> +- "/devSpecs/Beacon/specification/"
Shouldn't these be Person?

2021-11-22 09:47 UTC, AlasdairGray commented on pages/_profiles/Sample/0.2-RELEASE-2018_11_10.html
> +- "/devSpecs/Beacon/specification/"
Shouldn't these be Sample?

2021-11-22 16:16 UTC, ljgarcia commented on pages/_profiles/Event/0.2-DRAFT-2019_06_14.html
> +- "/devSpecs/Beacon/specification/"
Yes, fixed in latest commit

2021-11-22 16:16 UTC, ljgarcia commented on pages/_profiles/Person/0.2-DRAFT-2019_07_19.html
> +- "/devSpecs/Beacon/specification/"
Yes, fixed in latest commit

2021-11-22 16:16 UTC, ljgarcia commented on pages/_profiles/Sample/0.2-RELEASE-2018_11_10.html
> +- "/devSpecs/Beacon/specification/"
Yes, fixed in latest commit

2021-11-22 16:17 UTC, ljgarcia commented
Three profiles had the incorrect name in the redirection (Event, Person, Sample), now fixed.

2021-11-29 13:43 UTC, AlasdairGray approved these changes

2021-11-29 13:43 UTC, merged