Update next community call date
BioSchemas/bioschemas.github.io pull request #552
Opened 2022-06-13 15:14 UTC by AlasdairGray

2022-06-13 20:59 UTC, ljgarcia requested changes

2022-06-13 20:59 UTC, ljgarcia commented on index.html
> +call-date: 2022-06-25T15:00UTC
It should be 27th of June, should not it? 25th June is a Saturday, 27th is a Monday. Please double check the date.

2022-06-14 08:46 UTC, ivanmicetic approved these changes
Yes, 27 should be the correct day, I'll update it now

2022-06-14 08:50 UTC, ljgarcia approved these changes

2022-06-14 08:51 UTC, merged