New people added to _people
BioSchemas/bioschemas.github.io pull request #822
Opened 2024-08-01 13:48 UTC by selgebali

Added new people pages to tag in biosamples/samples

2024-08-13 13:59 UTC, gtsueng requested changes
@selgebali @nsjuty Do the leads need to be changed as well?

2024-08-20 11:09 UTC, nsjuty commented
I think it should be Sara. That ok with you @selgebali ?

2024-09-04 14:07 UTC, selgebali commented
I changed it! sorry I missed the leads! :)

2024-09-05 14:40 UTC, gtsueng approved these changes

2024-09-05 14:44 UTC, merged